### ISSUE TITLE
Feature: Option to export the calendar as an `.ics` file

### ISSUE THREAD

**Issue by zefr0x** [Radwan-Albahrani/Exam-Automation-IAU#1]
For compatibility with most calendar applications and easier sharing the [`Internet Calendaring and Scheduling Core Object Specification`](https://en.wikipedia.org/wiki/ICalendar) is a great solution.

Both [`icalendar`](https://pypi.org/project/icalendar/) and [`ics`](https://pypi.org/project/ics/) libraries are viable options for working with it in Python.

I haven't done much research about them, but the `icalendar` library is complex, and has a feature-rich iCalendar processing, while `ics` is simpler, lightweight and easier to use for simple projects.

**Comment by Radwan-Albahrani** [comment]
feature added
